version: "3.9"
services:
  es01:
    image: elasticsearch:8.3.1
    network_mode: bridge
    ports:
      - "9201:9201"
      - "9301:9301"
    networks:
      - "video-service"
    volumes:
      - ./node-1/data:/usr/share/elasticsearch/data
      - ./node-1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node-1/plugins:/usr/share/elasticsearch/plugins
      - ./node-1/logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  es02:
    image: elasticsearch:8.3.1
    network_mode: bridge
    ports:
      - "9202:9202"
      - "9302:9302"
    networks:
      - "video-service"
    volumes:
      - ./node-2/data:/usr/share/elasticsearch/data
      - ./node-2/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node-2/plugins:/usr/share/elasticsearch/plugins
      - ./node-2/logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  es03:
    image: elasticsearch:8.3.1
    network_mode: bridge
    ports:
      - "9203:9203"
      - "9303:9303"
    networks:
      - "video-service"
    volumes:
      - ./node-3/data:/usr/share/elasticsearch/data
      - ./node-3/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./node-3/plugins:/usr/share/elasticsearch/plugins
      - ./node-3/logs:/usr/share/elasticsearch/logs
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: kibana:8.3.1
    network_mode: bridge
    ports:
      - "5601:5601"
    networks:
      - "video-service"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  video-service:
    external: true